[ui]
hideTopBar = true
hideSidebarNav = true

[server]
enableStaticServing = false

[theme]
# 라이트 모드 색상 (기본 테마)
base = "light"
primaryColor = "#FF9900"  # AWS 주요 색상
backgroundColor = "#FFFFFF"  # 배경 (흰색)
secondaryBackgroundColor = "#F8F9FA"  # 챗봇 등 컴포넌트 배경
textColor = "#333333"  # 텍스트 색상

# 다크 모드 색상
[theme.dark]
primaryColor = "#FF9900"  # AWS 주요 색상 (동일)
backgroundColor = "#121212"  # 다크모드 배경
secondaryBackgroundColor = "#1E1E1E"  # 다크모드 컴포넌트 배경
textColor = "#E0E0E0"  # 다크모드 텍스트 색상
